version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
init:
  git config --global core.autocrlf true
before_build:
- ps: msbuild src /m /nologo /v:quiet /fl /t:restore
build_script:
- ps: msbuild src /m /nologo /v:minimal /fl /t:build,pack
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package
